<a href="https://colab.research.google.com/github/manuelrucci7/deep-learning-course/blob/main/colab/Pytorch_Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pytorch Intro

## Pytorch setup

* Local (Own Pc)

    Install [python 3.8](https://www.python.org/downloads/)

    ```
    pip3 install virtualenv
    virtualenv env
    source env/bin/activate # Linux - Mac
    source env/Scripts/activate # Windows
    pip install torch torchvision
    ```


* Google Colab

    ```
    pip3 install torch torchvision
    ```
These requirements should be arealdy satisied


In [ ]:
!nvidia-smi

Thu Mar  4 19:26:57 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.39       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   35C    P0    27W / 250W |      0MiB / 16280MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
# Verify installation
!pip list | grep torch

torch                         1.7.1+cu101   
torchsummary                  1.5.1         
torchtext                     0.3.1         
torchvision                   0.8.2+cu101   


In [ ]:
# Change runtime colab type to enable GPU
# Click on Runtime --> Select Change Runtime Type --> Select Hardware Accelarion GPU

import torch
import torchvision
print("Torch Version: ",torch.__version__)
print("Torch Vision Version:", torchvision.__version__)
print("Is Cuda available: ", torch.cuda.is_available())
print("Number of  Cuda device: ", torch.cuda.device_count())
print("Get Cuda Current device: ", torch.cuda.current_device())
print("Get Name of Cuda  device: ", torch.cuda.get_device_name(0))

Torch Version:  1.7.1+cu101
Torch Vision Version: 0.8.2+cu101
Is Cuda available:  True
Number of  Cuda device:  1
Get Cuda Current device:  0
Get Name of Cuda  device:  Tesla P100-PCIE-16GB


In [ ]:
torch.cuda.is_available()

True

In [ ]:
! pip3 install torch torchvision

## Pytorch: Tensors

> Tensor: n-dimensional array

* [Pytoch documentation](https://pytorch.org/docs/stable/index.html)
* [List of Pytorch Type](https://pytorch.org/docs/stable/tensors.html)

In [ ]:
import torch
import numpy as np
x = torch.ones((4,4), dtype=torch.float16)
#x = np.ones((4,4), dtype=np.float16)
print(x)
print("Shape: ", x.shape)
print("Type : ", x.dtype) # Torch default data type is torch.float32

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float16)
Shape:  torch.Size([4, 4])
Type :  torch.float16


In [ ]:
# Specify tensor type
x = 2*torch.ones((1,3,2), dtype=torch.int8)
print(x)
print("Shape: ", x.shape)
print("Type : ", x.dtype)

tensor([[[2, 2],
         [2, 2],
         [2, 2]]], dtype=torch.int8)
Shape:  torch.Size([1, 3, 2])
Type :  torch.int8


In [ ]:
# Change tensor type
x = torch.rand(3, dtype=torch.float32) # random uniform 0-1
x = 5*x # Multiply by 5
print("Tensor: %s , Type: %s " % (x, x.dtype))
x = x.type(torch.uint8) # change data type to unit8
print("Tensor: %s , Type: %s " % (x, x.dtype))

Tensor: tensor([3.8648, 3.3090, 3.7264]) , Type: torch.float32 
Tensor: tensor([3, 3, 3], dtype=torch.uint8) , Type: torch.uint8 


In [ ]:
# Tensor to numpy array
x = torch.sin( torch.rand(4) + 2*torch.rand(4) )
xnp = x.numpy()
print("Numpy Array: %s , Type: %s " % (xnp, xnp.dtype))

Numpy Array: [0.9982301 0.6028976 0.7176252 0.8889904] , Type: float32 


In [ ]:
# Numpy array to tensor
import numpy as np
xnp = np.sin( np.random.rand(4) + 2*np.random.rand(4) ) # Float64 by default numpy
print(xnp)
x = torch.from_numpy(xnp)
x = x.type(torch.float32)
print("Tensor: %s , Type: %s " % (x, x.dtype))

[0.87555113 0.62579561 0.79933828 0.97127132]
Tensor: tensor([0.8756, 0.6258, 0.7993, 0.9713]) , Type: torch.float32 


In [ ]:
# Moving tensor bettwen cpu and cuda device
# If u do not specify the device the tensorf will be hosted by default on cpu
x = torch.tensor([[1,3,4.4,5.6]]) # RAM
print("Tensor: %s , Type: %s ,Shape: %s, Device: %s" % (x.tolist(), x.dtype,x.shape,x.device))
if torch.cuda.is_available():
    device = torch.device("cuda:0")
    x = x.to(device)
    print("Tensor: %s , Type: %s ,Shape: %s, Device: %s" % (x.tolist(), x.dtype,x.shape,x.device))


Tensor: [[1.0, 3.0, 4.400000095367432, 5.599999904632568]] , Type: torch.float32 ,Shape: torch.Size([1, 4]), Device: cpu
Tensor: [[1.0, 3.0, 4.400000095367432, 5.599999904632568]] , Type: torch.float32 ,Shape: torch.Size([1, 4]), Device: cuda:0


In [ ]:
class myclass: # la classe è un contenitore (diverse funzioni)
    def __init__(self, lista):
        # Initial
        self.arr = np.array(lista, dtype=np.float32)
        #self.device = torch.device("cuda:0")
        self.device = torch.device("cpu")

    def arrayToTensor(self):
        x = torch.from_numpy(self.arr).to(self.device)
        return x
    def arrayDouble(self):
        x = self.arr*2
        return x

cl = myclass([5,7,8,9])
p1 = cl.arrayToTensor()
p2  = cl.arrayDouble()
print(p1.device,p2)

cr = myclass([5,16,2,9])
pr1 = cr.arrayToTensor()
pr2  = cr.arrayDouble()
print(pr1,pr2)

## Pytorch Linear Regression, Polynomial Feature, GPU

In [10]:
import plotly.graph_objects as go
import numpy as np
import torch

x = np.linspace(0,30, 1000) #np.array([4,5,6,8,12,18,22,23])
y = x**2+x
#y = x+4 + 4*np.random.rand(100)      # Try this

class fit_pytorch:
    def __init__(self, use_gpu, use_poly):
        self.use_gpu = use_gpu
        if self.use_gpu and torch.cuda.is_available():
            self.device = torch.device("cuda:0")
        else:
            self.device = torch.device("cpu")
        self.use_poly = use_poly
        self.B = None

    def fit(self,x,y):
        X = torch.tensor(x, dtype=torch.float32).reshape(-1,1)
        if self.use_poly:
            X = torch.cat((torch.ones(X.shape[0], 1), X, X**2,X**3,X**4), dim=1)
        else:
            X = torch.cat((torch.ones(X.shape[0], 1), X), dim=1)
        Y = torch.tensor(y, dtype=torch.float32).reshape(-1,1)
        X = X.to(self.device)
        Y = Y.to(self.device)
        self.B = torch.matmul(torch.matmul(torch.inverse(torch.matmul(X.T,X)),X.T),Y)

    def predict(self, x):
        if self.B is None:
            print("Fit the model first")
            return
        Xt = torch.tensor(x, dtype=torch.float32).reshape(-1,1)
        if self.use_poly:
            Xt = torch.cat((torch.ones(Xt.shape[0], 1), Xt, Xt**2,Xt**3,Xt**4), dim=1)
        else:
            Xt = torch.cat((torch.ones(Xt.shape[0], 1), Xt), dim=1)
        Xt = Xt.to(self.device)
        self.B = self.B.to(self.device)
        Yt = torch.matmul(Xt,self.B)
        yt = Yt.cpu().detach().numpy().reshape(-1)
        return yt

# Example standard linear regression
cl = fit_pytorch(use_gpu=True, use_poly=False)
cl.fit(x,y)
yt = cl.predict(x)

# Example linear regression gpu
clpoly = fit_pytorch(use_gpu=True, use_poly=True)
clpoly.fit(x,y)
ytpoly = clpoly.predict(x)

# Plot
fig = go.Figure(data=go.Scatter(x=x, y=y, mode="markers", name="y"))
fig.add_trace(go.Scatter(x=x, y=yt, mode="lines", name="y_hat"))
fig.add_trace(go.Scatter(x=x, y=ytpoly, mode="lines", name="y_hat_poly"))

fig.show()

## Pytorch Iterative Linear Regression

In [12]:
import plotly.graph_objects as go
import numpy as np
import torch

# Use the same class of before fit_pytorch

x = np.linspace(0,30, 1000) #np.array([4,5,6,8,12,18,22,23])
y = np.sin(x)
#y = x**2+x                           # Try this
#y = x+4 + 4*np.random.rand(100)      # Try this

fig = go.Figure(data=go.Scatter(x=x, y=y, mode="markers"))

cl = fit_pytorch(use_gpu=True, use_poly=False)

# do this every 10 points
num_points = 30 # try 10, 100
for i in range(0,len(x),num_points):
    xtemp = x[i:i+num_points]
    ytemp = y[i:i+num_points]

    cl.fit(xtemp,ytemp)
    yt = cl.predict(xtemp)

    fig.add_trace(go.Scatter(x=xtemp, y=yt, mode="lines"))

fig.show()